### ISSUE TITLE
Bad image in chapter 3.

### ISSUE THREAD

**Issue by dbecvarik** [prgcont/workshop-ASB#10]
Deployment config for hello-apb app probably uses wrong image, look at line 74:

      image: docker.io/ansibleplaybookbundle/hello-app-apb:latest

this should be probably image from  the apb push and local registry not from docker.io

**Comment by jwerak** [comment]
yes, got it, down side of bulk updates...

**Comment by dbecvarik** [comment]
fixed by #12
