### ISSUE TITLE
Complete "Setup Broker on minikube"

### ISSUE THREAD

**Issue by jwerak** [prgcont/workshop-ASB#4]
- Check prerequisites
- Start minikube
- Install service catalog using helm
  - Show what and where is running in k8s (pods, etc)
  - Introduce svcat utility 
  - Inspect k8s objects
- Install Ansible Service Broker
  - Show what and where is running in k8s (pods, etc)	
  - Check that apb tool is installed
  - Inspect broker
  - Inspect k8s objects

**Comment by jwerak** [comment]
PR here: https://github.com/prgcont/workshop-ASB/pull/8

**Comment by dbecvarik** [comment]
fixed by #9
