### ISSUE TITLE
Create "Operating Service Catalog" workshop section

### ISSUE THREAD

**Issue by jwerak** [prgcont/workshop-ASB#6]
- Deploying simple application
  - Etherpad
- Deploying bindable application
  - Deploy Wordpress app
    - Show its not working
  - Deploy postgres app
    - Show db is empty (kubectl exec)
  - Bind them
    - Show working app after bind
    - Show DB content (kubectl exec)

**Comment by dbecvarik** [comment]
fixed by #9
