### ISSUE TITLE
Add "Create Service Class via APB" workshop section

### ISSUE THREAD

**Issue by jwerak** [prgcont/workshop-ASB#7]
- Creating simple app using APB (https://github.com/ansibleplaybookbundle/ansible-playbook-bundle)
  - Provision
  - Deprovision
- Deploying to the broker
  - Show with svcat that its got deployed to catalog
- Deploy app to kubernetes
- Extend APB with parameters
  - Redeploy to broker
  - Deploy new version of app (second instance)
  - Show that app has parameter available

**Comment by dbecvarik** [comment]
fixed by #9
